import { titleCase } from "@/lib/utils/format";

import { Badge } from "@/components/ui/badge";

const variantMap: Record<string, Parameters<typeof Badge>[0]["variant"]> = {
  QUEUED: "secondary",
  PROCESSING: "warning",
  SENDING: "warning",
  COMPLETED: "success",
  ACTIVE: "success",
  READY: "success",
  SUCCESS: "success",
  SENT: "success",
  SCHEDULED: "secondary",
  CONTACTED: "secondary",
  BOOKED: "secondary",
  JOB_IN_PROGRESS: "warning",
  PARTIAL: "warning",
  FAILED: "destructive",
  CURRENT: "success",
  STALE: "warning",
  UNMAPPED: "outline",
  UNRESOLVED: "outline",
  MATCHED: "success",
  MANUAL_OVERRIDE: "warning",
  CONFLICT: "destructive",
  ERROR: "destructive",
  OPEN: "warning",
  RESOLVED: "success",
  IGNORED: "outline",
  LOW: "outline",
  MEDIUM: "secondary",
  HIGH: "warning",
  CRITICAL: "destructive",
  CANCELED: "outline",
  CLOSED_WON: "success",
  CLOSED_LOST: "destructive",
  ENDED: "outline",
  REQUESTED: "secondary",
  UNTESTED: "secondary",
  DRAFT: "outline",
  INACTIVE: "outline",
  SKIPPED: "outline",
  NOT_RECEIVED: "outline",
  NOT_TRIGGERED: "outline",
  UNKNOWN: "outline",
  UNREAD: "warning",
  READ: "secondary",
  REPLIED: "success"
};

const labelMap: Record<string, string> = {
  QUEUED: "Queued",
  PROCESSING: "In progress",
  SENDING: "Sending",
  COMPLETED: "Completed",
  ACTIVE: "Active",
  READY: "Ready",
  SUCCESS: "Succeeded",
  SENT: "Sent",
  SCHEDULED: "Scheduled",
  CONTACTED: "Contacted",
  BOOKED: "Booked",
  JOB_IN_PROGRESS: "Job in progress",
  PARTIAL: "Partial",
  FAILED: "Failed",
  CURRENT: "Current",
  STALE: "Stale",
  UNMAPPED: "Unmapped",
  UNRESOLVED: "Unresolved",
  MATCHED: "Matched",
  MANUAL_OVERRIDE: "Manual override",
  CONFLICT: "Conflict",
  ERROR: "Error",
  OPEN: "Open",
  RESOLVED: "Resolved",
  IGNORED: "Ignored",
  LOW: "Low",
  MEDIUM: "Medium",
  HIGH: "High",
  CRITICAL: "Critical",
  CANCELED: "Canceled",
  CLOSED_WON: "Closed won",
  CLOSED_LOST: "Closed lost",
  ENDED: "Ended",
  REQUESTED: "Requested",
  UNTESTED: "Untested",
  DRAFT: "Draft",
  INACTIVE: "Inactive",
  SKIPPED: "Skipped",
  NOT_RECEIVED: "No delivery",
  NOT_TRIGGERED: "Not triggered",
  UNKNOWN: "Unknown",
  UNREAD: "Unread",
  READ: "Read",
  REPLIED: "Replied"
};

export function StatusChip({ status }: { status: string }) {
  return <Badge className="whitespace-nowrap" variant={variantMap[status] ?? "outline"}>{labelMap[status] ?? titleCase(status)}</Badge>;
}
