ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'PLATFORM_ADMIN';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'AGENCY_OPERATOR';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'CLIENT_ADMIN';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'CLIENT_MANAGER';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'REVIEWER';
